<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Beyond the course - Data Science in Education</title>
  <meta name="renderer" content="webkit" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>

<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />

<meta name="theme-color" content="#f8f5ec" />
<meta name="msapplication-navbutton-color" content="#f8f5ec">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="#f8f5ec">


<meta name="author" content="Daniel Anderson" />
  <meta name="description" content="em { font-style: italic }   strong { font-weight: bold; }  A reminder: The R learning curve Agenda  Introduction to functions Introduction to Lists Introduction to the purrr package for working with lists Artificial example Walk through a real script (at least some of it)  Before we get started&amp;hellip;  There&amp;rsquo;s SO MUCH we still haven&amp;rsquo;t talked about
 Haven&amp;rsquo;t even discussed modeling! Version control (git/github) Functional programming (get a bit today) Object oriented programming  We also briefly discussed a few important topics" />

  <meta name="keywords" content="Data Science, Education, Data Visualization" />






<meta name="generator" content="Hugo 0.56.0" />


<link rel="canonical" href="/vita/classr/slides/w10p1/w10p1/" />

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">







<link href="/dist/even.min.css?v=3.0.1" rel="stylesheet">
<link href="/lib/fancybox/jquery.fancybox-3.1.20.min.css" rel="stylesheet">




<meta property="og:title" content="Beyond the course" />
<meta property="og:description" content="em { font-style: italic }   strong { font-weight: bold; }  A reminder: The R learning curve Agenda  Introduction to functions Introduction to Lists Introduction to the purrr package for working with lists Artificial example Walk through a real script (at least some of it)  Before we get started&hellip;  There&rsquo;s SO MUCH we still haven&rsquo;t talked about
 Haven&rsquo;t even discussed modeling! Version control (git/github) Functional programming (get a bit today) Object oriented programming  We also briefly discussed a few important topics" />
<meta property="og:type" content="article" />
<meta property="og:url" content="/vita/classr/slides/w10p1/w10p1/" />

<meta itemprop="name" content="Beyond the course">
<meta itemprop="description" content="em { font-style: italic }   strong { font-weight: bold; }  A reminder: The R learning curve Agenda  Introduction to functions Introduction to Lists Introduction to the purrr package for working with lists Artificial example Walk through a real script (at least some of it)  Before we get started&hellip;  There&rsquo;s SO MUCH we still haven&rsquo;t talked about
 Haven&rsquo;t even discussed modeling! Version control (git/github) Functional programming (get a bit today) Object oriented programming  We also briefly discussed a few important topics">



<meta itemprop="wordCount" content="6522">



<meta itemprop="keywords" content="" />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Beyond the course"/>
<meta name="twitter:description" content="em { font-style: italic }   strong { font-weight: bold; }  A reminder: The R learning curve Agenda  Introduction to functions Introduction to Lists Introduction to the purrr package for working with lists Artificial example Walk through a real script (at least some of it)  Before we get started&hellip;  There&rsquo;s SO MUCH we still haven&rsquo;t talked about
 Haven&rsquo;t even discussed modeling! Version control (git/github) Functional programming (get a bit today) Object oriented programming  We also briefly discussed a few important topics"/>

<!--[if lte IE 9]>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/classlist/1.1.20170427/classList.min.js"></script>
<![endif]-->

<!--[if lt IE 9]>
  <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
<![endif]-->

</head>
<body>
  <div id="mobile-navbar" class="mobile-navbar">
  <div class="mobile-header-logo">
    <a href="/" class="logo">datalorax</a>
  </div>
  <div class="mobile-navbar-icon">
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>
<nav id="mobile-menu" class="mobile-menu slideout-menu">
  <ul class="mobile-menu-list">
    <a href="/post/">
        <li class="mobile-menu-item">Archives</li>
      </a><a href="/tags/">
        <li class="mobile-menu-item">Tags</li>
      </a><a href="/categories/">
        <li class="mobile-menu-item">Categories</li>
      </a><a href="/about/">
        <li class="mobile-menu-item">About</li>
      </a><a href="/talks/talks/">
        <li class="mobile-menu-item">Talks</li>
      </a><a href="/vita/vita/">
        <li class="mobile-menu-item">Vita</li>
      </a>
  </ul>
</nav>
  <div class="container" id="mobile-panel">
    <header id="header" class="header">
        <div class="logo-wrapper">
  <a href="/" class="logo">datalorax</a>
</div>

<nav class="site-navbar">
  <ul id="menu" class="menu">
    <li class="menu-item">
        <a class="menu-item-link" href="/post/">Archives</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/tags/">Tags</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/categories/">Categories</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/about/">About</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/talks/talks/">Talks</a>
      </li><li class="menu-item">
        <a class="menu-item-link" href="/vita/vita/">Vita</a>
      </li>
  </ul>
</nav>

    </header>

    <main id="main" class="main">
      <div class="content-wrapper">
        <div id="content" class="content">
          <article class="post">
  <div class="post-content">
      

<style>
em {
  font-style: italic
}
</style>

<style>
strong {
  font-weight: bold;
}
</style>

<h2 id="a-reminder-the-r-learning-curve">A reminder: The R learning curve</h2>

<p><img src="../assets/fig/unnamed-chunk-1-1.png" alt="plot of chunk unnamed-chunk-1" /></p>

<hr />

<h2 id="agenda">Agenda</h2>

<ul>
<li>Introduction to functions</li>
<li>Introduction to Lists</li>
<li>Introduction to the <em>purrr</em> package for working with lists</li>
<li>Artificial example</li>
<li>Walk through a real script (at least some of it)</li>
</ul>

<hr />

<h2 id="before-we-get-started">Before we get started&hellip;</h2>

<ul>
<li><p>There&rsquo;s SO MUCH we still haven&rsquo;t talked about</p>

<ul>
<li>Haven&rsquo;t even discussed modeling!</li>
<li>Version control (git/github)</li>
<li>Functional programming (get a bit today)</li>
<li>Object oriented programming</li>
</ul></li>

<li><p>We also briefly discussed a few important topics</p>

<ul>
<li>Text manipulations/factors/dates</li>
<li>Data structures besides data frames</li>
</ul></li>
</ul>

<p>Todays&rsquo;s lecture is on the next really big topic I&rsquo;d recommend you dive into, once you feel comfortable with most of what we&rsquo;ve covered in this class: Functions and loops</p>

<hr />

<h1 id="functions">functions</h1>

<hr />

<h2 id="writing-functions-a-basic-example">Writing functions: A basic example</h2>

<pre><code class="language-r">pow &lt;- function(x, power) {
	x^power
}
</code></pre>

<p>This function takes two arguments: <code>x</code> and <code>power</code>, with <code>x</code> being a generic
  numeric vector (could be a scalar), and power being the power to which the number or vector will be raised (could also be a vector).</p>

<p>While the function appears (and is) simple, it is actually quite flexible.</p>

<pre><code class="language-r">pow(x = 2, power = 3)
</code></pre>

<pre><code>## [1] 8
</code></pre>

<pre><code class="language-r">pow(c(3, 5, 7), 9)
</code></pre>

<pre><code>## [1]    19683  1953125 40353607
</code></pre>

<pre><code class="language-r">pow(c(7, 1, -5, 8), c(2, 3))
</code></pre>

<pre><code>## [1]  49   1  25 512
</code></pre>

<pre><code class="language-r">pow(c(8, 5), c(3, 5))
</code></pre>

<pre><code>## [1]  512 3125
</code></pre>

<pre><code class="language-r">pow(8, c(5, 3, 2))
</code></pre>

<pre><code>## [1] 32768   512    64
</code></pre>

<hr />

<h2 id="why-is-this-so-powerful">Why is this so powerful?</h2>

<ul>
<li>This is what makes R a programming language, rather than a GUI</li>
<li>You can program R to do anything

<ul>
<li>Scrape data from the web (<em>rvest</em>, <em>twitteR</em>, <em>rtweet</em>,  <em>tuber</em>)</li>
<li>Complex visualizations (<em>ggplot</em>, <em>lattice</em>, <em>visreg</em>)</li>
<li>Any analysis (<em>lme4</em>, <em>randomForest</em>, <em>gamm4</em>)</li>
</ul></li>
</ul>

<hr />

<h2 id="calculate-cohen-s-d">Calculate Cohen&rsquo;s <em>d</em></h2>

<ul>
<li>Suppose we wanted to write a function: What would be the arguments we&rsquo;d need?</li>
</ul>

<p>$$
d = \frac{\bar{X}<em>{foc} - \bar{X}</em>{ref}}{\sqrt{\frac{(n<em>{foc} - 1)Var</em>{foc} + (n<em>{ref} - 1)Var</em>{ref}}{n<em>{foc} + n</em>{ref} - 2}}}
$$</p>

<ul>
<li>Start simple: Let&rsquo;s write a function to compute mean differences</li>
<li>Think about what format you&rsquo;d expect the data to come in</li>
</ul>

<hr />

<ul>
<li><p>For simplicity, let&rsquo;s assume separate columns for the focal and reference group</p>

<pre><code class="language-r">mean_diff &lt;- function(foc, ref) {
	mean(foc, na.rm = TRUE) - mean(ref, na.rm = TRUE)
}
</code></pre></li>
</ul>

<hr />

<h2 id="test-it-out">Test it out</h2>

<pre><code class="language-r">test_df &lt;- data.frame(group1 = rnorm(n = 100, mean = 10, sd = 1),
					  group2 = rnorm(n = 100, mean = 8, sd = 1))
head(test_df)
</code></pre>

<pre><code>##      group1   group2
## 1 10.079855 7.775533
## 2  9.848619 7.269473
## 3 10.865970 8.058229
## 4 10.663259 9.267586
## 5 10.181277 7.761954
## 6  9.030272 8.705604
</code></pre>

<hr />

<pre><code class="language-r">mean_diff(test_df$group1, test_df$group2)
</code></pre>

<pre><code>## [1] 1.981619
</code></pre>

<pre><code class="language-r">mean_diff(rnorm(100, 10), rnorm(100, 12))
</code></pre>

<pre><code>## [1] -2.129773
</code></pre>

<pre><code class="language-r">mean_diff(rnorm(100, 9), rnorm(100, 90))
</code></pre>

<pre><code>## [1] -80.95977
</code></pre>

<hr />

<h2 id="now-let-s-build-the-denominator">Now let&rsquo;s build the denominator</h2>

<p>$$\sqrt{\frac{(n<em>{foc} - 1)Var</em>{foc} + (n<em>{ref} - 1)Var</em>{ref}}
                  {n<em>{foc} + n</em>{ref} - 2}}$$</p>

<pre><code class="language-r">pooled_sd &lt;- function(foc, ref) {
	n_foc &lt;- length(na.omit(foc))
	n_ref &lt;- length(na.omit(ref))

	v_foc &lt;- var(foc, na.rm = TRUE)
	v_ref &lt;- var(ref, na.rm = TRUE)

	sqrt( ((n_foc - 1)*v_foc + (n_ref - 1)*v_ref) / ( (n_foc + n_ref) - 2) )

}
</code></pre>

<hr />

<h2 id="put-them-together">Put them together</h2>

<pre><code class="language-r">coh_d &lt;- function(foc, ref) {
	mean_diff(foc, ref) / pooled_sd(foc, ref)
}
coh_d(test_df$group1, test_df$group2)
</code></pre>

<pre><code>## [1] 2.054554
</code></pre>

<pre><code class="language-r">coh_d(rnorm(100, 10), rnorm(180, 12, 20))
</code></pre>

<pre><code>## [1] -0.03242877
</code></pre>

<hr />

<h1 id="testing-out-functions-demo">Testing out functions demo</h1>

<hr />

<h2 id="when-do-you-write-a-function">When do you write a function?</h2>

<ul>
<li>General rule of thumb - if you copy and paste more than three times, might want to write a function</li>
<li>Functions written for interactive purposes can depend on objects in your global environment</li>
</ul>

<hr />

<h2 id="quick-contrived-example">Quick contrived example</h2>

<p>Calculate one standard deviation below the mean for each column</p>

<pre><code class="language-r">mtcars
</code></pre>

<pre><code>##                      mpg cyl  disp  hp drat    wt  qsec vs am gear carb
## Mazda RX4           21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
## Mazda RX4 Wag       21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
## Datsun 710          22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
## Hornet 4 Drive      21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
## Hornet Sportabout   18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
## Valiant             18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
## Duster 360          14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
## Merc 240D           24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
## Merc 230            22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
## Merc 280            19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4
## Merc 280C           17.8   6 167.6 123 3.92 3.440 18.90  1  0    4    4
## Merc 450SE          16.4   8 275.8 180 3.07 4.070 17.40  0  0    3    3
## Merc 450SL          17.3   8 275.8 180 3.07 3.730 17.60  0  0    3    3
## Merc 450SLC         15.2   8 275.8 180 3.07 3.780 18.00  0  0    3    3
## Cadillac Fleetwood  10.4   8 472.0 205 2.93 5.250 17.98  0  0    3    4
## Lincoln Continental 10.4   8 460.0 215 3.00 5.424 17.82  0  0    3    4
## Chrysler Imperial   14.7   8 440.0 230 3.23 5.345 17.42  0  0    3    4
## Fiat 128            32.4   4  78.7  66 4.08 2.200 19.47  1  1    4    1
## Honda Civic         30.4   4  75.7  52 4.93 1.615 18.52  1  1    4    2
## Toyota Corolla      33.9   4  71.1  65 4.22 1.835 19.90  1  1    4    1
## Toyota Corona       21.5   4 120.1  97 3.70 2.465 20.01  1  0    3    1
## Dodge Challenger    15.5   8 318.0 150 2.76 3.520 16.87  0  0    3    2
## AMC Javelin         15.2   8 304.0 150 3.15 3.435 17.30  0  0    3    2
## Camaro Z28          13.3   8 350.0 245 3.73 3.840 15.41  0  0    3    4
## Pontiac Firebird    19.2   8 400.0 175 3.08 3.845 17.05  0  0    3    2
## Fiat X1-9           27.3   4  79.0  66 4.08 1.935 18.90  1  1    4    1
## Porsche 914-2       26.0   4 120.3  91 4.43 2.140 16.70  0  1    5    2
## Lotus Europa        30.4   4  95.1 113 3.77 1.513 16.90  1  1    5    2
## Ford Pantera L      15.8   8 351.0 264 4.22 3.170 14.50  0  1    5    4
## Ferrari Dino        19.7   6 145.0 175 3.62 2.770 15.50  0  1    5    6
## Maserati Bora       15.0   8 301.0 335 3.54 3.570 14.60  0  1    5    8
## Volvo 142E          21.4   4 121.0 109 4.11 2.780 18.60  1  1    4    2
</code></pre>

<hr />

<h2 id="one-method-avoid-writing-a-function-at-all">One method - avoid writing a function at all</h2>

<pre><code class="language-r">library(tidyverse)
mtcars %&gt;% 
	gather(var, val) %&gt;% 
	group_by(var) %&gt;% 
	summarize(low = min(val) - sd(val))
</code></pre>

<pre><code>## # A tibble: 11 x 2
##      var         low
##    &lt;chr&gt;       &lt;dbl&gt;
##  1    am  -0.4989909
##  2  carb  -0.6152000
##  3   cyl   2.2140784
##  4  disp -52.8386938
##  5  drat   2.2253213
##  6  gear   2.2621959
##  7    hp -16.5628685
##  8   mpg   4.3730519
##  9  qsec  12.7130568
## 10    vs  -0.5040161
## 11    wt   0.5345426
</code></pre>

<hr />

<h2 id="another-method-copy-and-paste">Another method - copy and paste</h2>

<pre><code class="language-r">summarize(mtcars, low = min(mpg) - sd(mpg))
</code></pre>

<pre><code>##        low
## 1 4.373052
</code></pre>

<pre><code class="language-r">summarize(mtcars, low = min(cyl) - sd(cyl))
</code></pre>

<pre><code>##        low
## 1 2.214078
</code></pre>

<pre><code class="language-r">summarize(mtcars, low = min(disp) - sd(disp))
</code></pre>

<pre><code>##         low
## 1 -52.83869
</code></pre>

<pre><code class="language-r">summarize(mtcars, low = min(hp) - sd(hp))
</code></pre>

<pre><code>##         low
## 1 -16.56287
</code></pre>

<pre><code class="language-r">summarize(mtcars, low = min(drat) - sd(drat))
</code></pre>

<pre><code>##        low
## 1 2.225321
</code></pre>

<p>&hellip;</p>

<hr />

<h2 id="write-a-function">Write a function</h2>

<pre><code class="language-r">low &lt;- function(var) {
	min(mtcars[[var]]) - sd(mtcars[[var]])
}
low(&quot;mpg&quot;)
</code></pre>

<pre><code>## [1] 4.373052
</code></pre>

<hr />

<h2 id="loop-the-function-through">Loop the function through</h2>

<pre><code class="language-r">for(i in seq_along(names(mtcars))) {
	print( low(names(mtcars)[i]) )
}
</code></pre>

<pre><code>## [1] 4.373052
## [1] 2.214078
## [1] -52.83869
## [1] -16.56287
## [1] 2.225321
## [1] 0.5345426
## [1] 12.71306
## [1] -0.5040161
## [1] -0.4989909
## [1] 2.262196
## [1] -0.6152
</code></pre>

<hr />

<h2 id="when-writing-functions">When writing functions</h2>

<ul>
<li>You may run into some problems with tidyverse syntax (non-standard evaluation)</li>
<li>If you&rsquo;re writing functions for others to use, it is generally best to avoid external dependencies anyway, when you can

<ul>
<li>That said, if relying on an external dependency substantially speeds up your code, makes it more clear, etc., it is probably be worth it.</li>
</ul></li>
<li>If you really want to jump into the programming side of things, probably best to learn some base R (I&rsquo;d recommend Hadley&rsquo;s books: <a href="http://adv-r.had.co.nz">Advanced R</a> and <a href="http://r-pkgs.had.co.nz">R Packages</a>)</li>
</ul>

<hr />

<h2 id="if-you-want-to-use-tidyverse-in-programming">If you want to use tidyverse in programming&hellip;</h2>

<p>You have to use <em>tidyeval</em> concepts. For example you would probably think the following would work, but it fails:</p>

<pre><code class="language-r">library(tidyverse)

grouped_means &lt;- function(group) {
  mtcars %&gt;% 
    group_by(group) %&gt;% 
    summarize(mpg = mean(mpg))
} 
grouped_means(cyl)
</code></pre>

<pre><code>## Error in grouped_df_impl(data, unname(vars), drop): Column `group` is unknown
</code></pre>

<hr />

<h2 id="maybe-quote-it">Maybe quote it?</h2>

<pre><code class="language-r">grouped_means(&quot;cyl&quot;)
</code></pre>

<pre><code>## Error in grouped_df_impl(data, unname(vars), drop): Column `group` is unknown
</code></pre>

<ul>
<li>We&rsquo;re still getting errors because of <em>Non-standard evaluation</em>.<br /></li>
<li>I&rsquo;ll briefly discuss this, but I would recommend avoiding it until you feel pretty comfortable with functions.</li>
</ul>

<hr />

<h2 id="problem">Problem</h2>

<ul>
<li>You can&rsquo;t pass a bare variable name to a function without quoting it (not <code>&quot;&quot;</code>,
but capturing it with <code>quote</code>).</li>
<li>BUT, even this won&rsquo;t work because tidyverse functions already do the quoting for us in the background.</li>
</ul>

<h1 id="process">Process</h1>

<ul>
<li>Quote the input to capture the argument</li>
<li>Tell the tidyverse functions it has already been quoted so it doesn&rsquo;t try to quote it again.</li>
</ul>

<hr />

<h2 id="back-to-previous-example">Back to previous example</h2>

<pre><code class="language-r">grouped_means &lt;- function(group) {
  group_var &lt;- enquo(group)
  
  mtcars %&gt;% 
    group_by(!!group_var) %&gt;% 
    summarize(mpg = mean(mpg))
} 
grouped_means(cyl)
</code></pre>

<pre><code>## # A tibble: 3 x 2
##     cyl      mpg
##   &lt;dbl&gt;    &lt;dbl&gt;
## 1     4 26.66364
## 2     6 19.74286
## 3     8 15.10000
</code></pre>

<hr />

<pre><code class="language-r">grouped_means(gear)
</code></pre>

<pre><code>## # A tibble: 3 x 2
##    gear      mpg
##   &lt;dbl&gt;    &lt;dbl&gt;
## 1     3 16.10667
## 2     4 24.53333
## 3     5 21.38000
</code></pre>

<pre><code class="language-r">grouped_means(vs)
</code></pre>

<pre><code>## # A tibble: 2 x 2
##      vs      mpg
##   &lt;dbl&gt;    &lt;dbl&gt;
## 1     0 16.61667
## 2     1 24.55714
</code></pre>

<p>Want to learn more? Look <a href="http://dplyr.tidyverse.org/articles/programming.html">here</a></p>

<hr />

<h2 id="quick-ish">Quick-ish</h2>

<p>The formula for calculating the mean is</p>

<p>$$\bar{x} = \frac{\Sigma x_i}{n}$$</p>

<ul>
<li>Write a function that calculates the sample mean, $\bar{x}$, but removes missing data by default</li>
<li>Only restriction: You can&rsquo;t use the <code>mean</code> function in your function (and you also probably want to call it something other than <code>mean</code>)</li>
<li>Compare the results of your function with <code>mean()</code>. Do the results match?</li>
</ul>

<hr />

<ul>
<li><p>Write the function</p>

<pre><code class="language-r">xbar &lt;- function(x) {
	x &lt;- na.omit(x)
	sum(x) / length(x)
}
</code></pre></li>

<li><p>Test it out: No missing data</p>

<pre><code class="language-r">xbar(mtcars$mpg); mean(mtcars$mpg)
</code></pre>

<pre><code>## [1] 20.09062
</code></pre>

<pre><code>## [1] 20.09062
</code></pre>

<pre><code class="language-r">xbar(mtcars$drat); mean(mtcars$drat)
</code></pre>

<pre><code>## [1] 3.596563
</code></pre>

<pre><code>## [1] 3.596563
</code></pre></li>
</ul>

<hr />

<ul>
<li><p>Test it out: missing data</p>

<pre><code class="language-r">v1 &lt;- c(1:5, NA, NA, 7:10)
v2 &lt;- c(NA, seq(32:80), NA, 12)
</code></pre>

<pre><code class="language-r">xbar(v1); mean(v1, na.rm = TRUE)
</code></pre>

<pre><code>## [1] 5.444444
</code></pre>

<pre><code>## [1] 5.444444
</code></pre>

<pre><code class="language-r">xbar(v2); mean(v2, na.rm = TRUE)
</code></pre>

<pre><code>## [1] 24.74
</code></pre>

<pre><code>## [1] 24.74
</code></pre></li>
</ul>

<hr />

<h2 id="another-alternative">Another alternative</h2>

<pre><code class="language-r">xbar &lt;- function(x) {
	sum(x, na.rm = TRUE) / length(na.omit(x))
}
</code></pre>

<hr />

<h2 id="writing-packages">Writing packages</h2>

<ul>
<li>It&rsquo;s not that hard!</li>
<li>Once you start writing more generic functions, and start to get fluent with them, you can write a package

<ul>
<li>This is the hard part - much harder than writing packages</li>
</ul></li>
<li>Write your own personal R package to start</li>
<li>Good resource for getting started: <a href="https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/">https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/</a></li>
</ul>

<p>You can do it! I promise!</p>

<hr />

<h1 id="lists">lists</h1>

<hr />

<h2 id="lists-versus-other-data-structures">Lists versus other data structures</h2>

<ul>
<li>To date, we have mostly worked with data frames

<ul>
<li>type of list</li>
</ul></li>
<li>Each column of a data frame is (almost always) an atomic vector of a specific type

<ul>
<li>double</li>
<li>integer</li>
<li>character</li>
<li>logical</li>
</ul></li>
<li>All elements within an atomic vector must be of the same type (implicit coercion).</li>
<li>Lists are vectors (not atomic) where every element can be of a different type, including other lists.</li>
</ul>

<hr />

<h2 id="contrasting-lists-and-atomic-vectors">Contrasting lists and atomic vectors</h2>

<h1 id="lists-1">Lists</h1>

<pre><code class="language-r">list(&quot;a&quot;, 4.35, TRUE, 7L)
</code></pre>

<pre><code>## [[1]]
## [1] &quot;a&quot;
## 
## [[2]]
## [1] 4.35
## 
## [[3]]
## [1] TRUE
## 
## [[4]]
## [1] 7
</code></pre>

<h1 id="vectors">Vectors</h1>

<p>(implicit coercion)</p>

<pre><code class="language-r">c(&quot;a&quot;, 4.35, TRUE, 7L)
</code></pre>

<pre><code>## [1] &quot;a&quot;    &quot;4.35&quot; &quot;TRUE&quot; &quot;7&quot;
</code></pre>

<pre><code class="language-r">c(4.35, TRUE, 7L)
</code></pre>

<pre><code>## [1] 4.35 1.00 7.00
</code></pre>

<hr />

<h2 id="lists-2">Lists</h2>

<p>Note that the length of list elements can all be different.</p>

<pre><code class="language-r">l &lt;- list(
	c(&quot;a&quot;, &quot;b&quot;, &quot;c&quot;),
	1:5,
	rep(c(T,F), 7),
	rnorm(3, 100, 25)
		  )
</code></pre>

<pre><code class="language-r">l
</code></pre>

<pre><code>## [[1]]
## [1] &quot;a&quot; &quot;b&quot; &quot;c&quot;
## 
## [[2]]
## [1] 1 2 3 4 5
## 
## [[3]]
##  [1]  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE
## [12] FALSE  TRUE FALSE
## 
## [[4]]
## [1] 69.01684 63.50577 98.50681
</code></pre>

<hr />

<h2 id="lists-returned-by-functions">Lists returned by functions</h2>

<ul>
<li><p>Many functions return a list of objects. This is because lists are a great way to store a lot of varied information. For example: <code>lm</code>.</p>

<pre><code class="language-r">mod &lt;- lm(hp ~ mpg, data = mtcars)
str(mod)
</code></pre>

<pre><code>## List of 12
##  $ coefficients : Named num [1:2] 324.08 -8.83
##   ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;(Intercept)&quot; &quot;mpg&quot;
##  $ residuals    : Named num [1:32] -28.7 -28.7 -29.8 -25.1 16 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:32] &quot;Mazda RX4&quot; &quot;Mazda RX4 Wag&quot; &quot;Datsun 710&quot; &quot;Hornet 4 Drive&quot; ...
##  $ effects      : Named num [1:32] -829.8 296.3 -23.6 -20 19.3 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:32] &quot;(Intercept)&quot; &quot;mpg&quot; &quot;&quot; &quot;&quot; ...
##  $ rank         : int 2
##  $ fitted.values: Named num [1:32] 139 139 123 135 159 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:32] &quot;Mazda RX4&quot; &quot;Mazda RX4 Wag&quot; &quot;Datsun 710&quot; &quot;Hornet 4 Drive&quot; ...
##  $ assign       : int [1:2] 0 1
##  $ qr           :List of 5
##   ..$ qr   : num [1:32, 1:2] -5.657 0.177 0.177 0.177 0.177 ...
##   .. ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. .. ..$ : chr [1:32] &quot;Mazda RX4&quot; &quot;Mazda RX4 Wag&quot; &quot;Datsun 710&quot; &quot;Hornet 4 Drive&quot; ...
##   .. .. ..$ : chr [1:2] &quot;(Intercept)&quot; &quot;mpg&quot;
##   .. ..- attr(*, &quot;assign&quot;)= int [1:2] 0 1
##   ..$ qraux: num [1:2] 1.18 1.02
##   ..$ pivot: int [1:2] 1 2
##   ..$ tol  : num 1e-07
##   ..$ rank : int 2
##   ..- attr(*, &quot;class&quot;)= chr &quot;qr&quot;
##  $ df.residual  : int 30
##  $ xlevels      : Named list()
##  $ call         : language lm(formula = hp ~ mpg, data = mtcars)
##  $ terms        :Classes 'terms', 'formula'  language hp ~ mpg
##   .. ..- attr(*, &quot;variables&quot;)= language list(hp, mpg)
##   .. ..- attr(*, &quot;factors&quot;)= int [1:2, 1] 0 1
##   .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. .. .. ..$ : chr [1:2] &quot;hp&quot; &quot;mpg&quot;
##   .. .. .. ..$ : chr &quot;mpg&quot;
##   .. ..- attr(*, &quot;term.labels&quot;)= chr &quot;mpg&quot;
##   .. ..- attr(*, &quot;order&quot;)= int 1
##   .. ..- attr(*, &quot;intercept&quot;)= int 1
##   .. ..- attr(*, &quot;response&quot;)= int 1
##   .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt; 
##   .. ..- attr(*, &quot;predvars&quot;)= language list(hp, mpg)
##   .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:2] &quot;numeric&quot; &quot;numeric&quot;
##   .. .. ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;hp&quot; &quot;mpg&quot;
##  $ model        :'data.frame':	32 obs. of  2 variables:
##   ..$ hp : num [1:32] 110 110 93 110 175 105 245 62 95 123 ...
##   ..$ mpg: num [1:32] 21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 ...
##   ..- attr(*, &quot;terms&quot;)=Classes 'terms', 'formula'  language hp ~ mpg
##   .. .. ..- attr(*, &quot;variables&quot;)= language list(hp, mpg)
##   .. .. ..- attr(*, &quot;factors&quot;)= int [1:2, 1] 0 1
##   .. .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. .. .. .. ..$ : chr [1:2] &quot;hp&quot; &quot;mpg&quot;
##   .. .. .. .. ..$ : chr &quot;mpg&quot;
##   .. .. ..- attr(*, &quot;term.labels&quot;)= chr &quot;mpg&quot;
##   .. .. ..- attr(*, &quot;order&quot;)= int 1
##   .. .. ..- attr(*, &quot;intercept&quot;)= int 1
##   .. .. ..- attr(*, &quot;response&quot;)= int 1
##   .. .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment: R_GlobalEnv&gt; 
##   .. .. ..- attr(*, &quot;predvars&quot;)= language list(hp, mpg)
##   .. .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:2] &quot;numeric&quot; &quot;numeric&quot;
##   .. .. .. ..- attr(*, &quot;names&quot;)= chr [1:2] &quot;hp&quot; &quot;mpg&quot;
##  - attr(*, &quot;class&quot;)= chr &quot;lm&quot;
</code></pre></li>
</ul>

<hr />

<p>You can access the elements through the list</p>

<pre><code class="language-r">mod$coefficients
</code></pre>

<pre><code>## (Intercept)         mpg 
##  324.082314   -8.829731
</code></pre>

<pre><code class="language-r">mod$residuals
</code></pre>

<pre><code>##           Mazda RX4       Mazda RX4 Wag          Datsun 710 
##         -28.6579634         -28.6579634         -29.7644476 
##      Hornet 4 Drive   Hornet Sportabout             Valiant 
##         -25.1260710          16.0336553         -59.2641833 
##          Duster 360           Merc 240D            Merc 230 
##          47.1828390         -46.6368780         -27.7644476 
##            Merc 280           Merc 280C          Merc 450SE 
##         -31.5514792         -43.9131026           0.7252741 
##          Merc 450SL         Merc 450SLC  Cadillac Fleetwood 
##           8.6720320          -9.8704031         -27.2531119 
## Lincoln Continental   Chrysler Imperial            Fiat 128 
##         -17.2531119          35.7147314          28.0009699 
##         Honda Civic      Toyota Corolla       Toyota Corona 
##          -3.6584921          40.2455664         -37.2430979 
##    Dodge Challenger         AMC Javelin          Camaro Z28 
##         -37.2214838         -39.8704031          38.3531080 
##    Pontiac Firebird           Fiat X1-9       Porsche 914-2 
##          20.4485208         -17.0306581          -3.5093084 
##        Lotus Europa      Ford Pantera L        Ferrari Dino 
##          57.3415079          79.4274355          24.8633863 
##       Maserati Bora          Volvo 142E 
##         143.3636507         -26.1260710
</code></pre>

<hr />

<h2 id="other-functions-will-transform-data-into-lists">Other functions will transform data into lists</h2>

<pre><code class="language-r">cyls &lt;- split(mtcars, mtcars$cyl)
str(cyls)
</code></pre>

<pre><code>## List of 3
##  $ 4:'data.frame':	11 obs. of  11 variables:
##   ..$ mpg : num [1:11] 22.8 24.4 22.8 32.4 30.4 33.9 21.5 27.3 26 30.4 ...
##   ..$ cyl : num [1:11] 4 4 4 4 4 4 4 4 4 4 ...
##   ..$ disp: num [1:11] 108 146.7 140.8 78.7 75.7 ...
##   ..$ hp  : num [1:11] 93 62 95 66 52 65 97 66 91 113 ...
##   ..$ drat: num [1:11] 3.85 3.69 3.92 4.08 4.93 4.22 3.7 4.08 4.43 3.77 ...
##   ..$ wt  : num [1:11] 2.32 3.19 3.15 2.2 1.61 ...
##   ..$ qsec: num [1:11] 18.6 20 22.9 19.5 18.5 ...
##   ..$ vs  : num [1:11] 1 1 1 1 1 1 1 1 0 1 ...
##   ..$ am  : num [1:11] 1 0 0 1 1 1 0 1 1 1 ...
##   ..$ gear: num [1:11] 4 4 4 4 4 4 3 4 5 5 ...
##   ..$ carb: num [1:11] 1 2 2 1 2 1 1 1 2 2 ...
##  $ 6:'data.frame':	7 obs. of  11 variables:
##   ..$ mpg : num [1:7] 21 21 21.4 18.1 19.2 17.8 19.7
##   ..$ cyl : num [1:7] 6 6 6 6 6 6 6
##   ..$ disp: num [1:7] 160 160 258 225 168 ...
##   ..$ hp  : num [1:7] 110 110 110 105 123 123 175
##   ..$ drat: num [1:7] 3.9 3.9 3.08 2.76 3.92 3.92 3.62
##   ..$ wt  : num [1:7] 2.62 2.88 3.21 3.46 3.44 ...
##   ..$ qsec: num [1:7] 16.5 17 19.4 20.2 18.3 ...
##   ..$ vs  : num [1:7] 0 0 1 1 1 1 0
##   ..$ am  : num [1:7] 1 1 0 0 0 0 1
##   ..$ gear: num [1:7] 4 4 3 3 4 4 5
##   ..$ carb: num [1:7] 4 4 1 1 4 4 6
##  $ 8:'data.frame':	14 obs. of  11 variables:
##   ..$ mpg : num [1:14] 18.7 14.3 16.4 17.3 15.2 10.4 10.4 14.7 15.5 15.2 ...
##   ..$ cyl : num [1:14] 8 8 8 8 8 8 8 8 8 8 ...
##   ..$ disp: num [1:14] 360 360 276 276 276 ...
##   ..$ hp  : num [1:14] 175 245 180 180 180 205 215 230 150 150 ...
##   ..$ drat: num [1:14] 3.15 3.21 3.07 3.07 3.07 2.93 3 3.23 2.76 3.15 ...
##   ..$ wt  : num [1:14] 3.44 3.57 4.07 3.73 3.78 ...
##   ..$ qsec: num [1:14] 17 15.8 17.4 17.6 18 ...
##   ..$ vs  : num [1:14] 0 0 0 0 0 0 0 0 0 0 ...
##   ..$ am  : num [1:14] 0 0 0 0 0 0 0 0 0 0 ...
##   ..$ gear: num [1:14] 3 3 3 3 3 3 3 3 3 3 ...
##   ..$ carb: num [1:14] 2 4 3 3 3 4 4 4 2 2 ...
</code></pre>

<hr />

<h2 id="more-on-lists">More on lists</h2>

<ul>
<li>Note that the previous slide looked like a nested list (list inside a list).
This is because data frames are lists, where each element of the list is a
vector of the same length.</li>
<li>lists are tremendously useful and flexible, and can lead to massive jumps in efficiency when combined with loops

<ul>
<li>Often want to loop through a list and apply a function to each element
of the list.</li>
</ul></li>
</ul>

<hr />

<h2 id="lists-and-data-frames">Lists and data frames</h2>

<pre><code class="language-r">l &lt;- list(
	lets = letters[1:5],
	ints = 9:5,
	dbl = rnorm(5, 12, 0.75)
	)
l
</code></pre>

<pre><code>## $lets
## [1] &quot;a&quot; &quot;b&quot; &quot;c&quot; &quot;d&quot; &quot;e&quot;
## 
## $ints
## [1] 9 8 7 6 5
## 
## $dbl
## [1] 11.11093 11.67222 11.55736 11.03530 11.02976
</code></pre>

<pre><code class="language-r">as.data.frame(l)
</code></pre>

<pre><code>##   lets ints      dbl
## 1    a    9 11.11093
## 2    b    8 11.67222
## 3    c    7 11.55736
## 4    d    6 11.03530
## 5    e    5 11.02976
</code></pre>

<hr />

<h1 id="alternative">Alternative</h1>

<pre><code class="language-r">dframe &lt;- data.frame(
	lets = letters[1:5],
	ints = 9:5,
	dbl = rnorm(5, 12, 0.75)
	)
dframe
</code></pre>

<pre><code>##   lets ints      dbl
## 1    a    9 12.27340
## 2    b    8 12.02279
## 3    c    7 11.72385
## 4    d    6 12.88239
## 5    e    5 12.46470
</code></pre>

<pre><code class="language-r">as.list(dframe)
</code></pre>

<pre><code>## $lets
## [1] a b c d e
## Levels: a b c d e
## 
## $ints
## [1] 9 8 7 6 5
## 
## $dbl
## [1] 12.27340 12.02279 11.72385 12.88239 12.46470
</code></pre>

<hr />

<h1 id="brief-introduction-to-purrr">Brief introduction to <em>purrr</em></h1>

<p><img src="../assets/img/purrr.png" alt="purr" /></p>

<hr />

<h2 id="purrr"><em>purrr</em></h2>

<ul>
<li>As everything with the tidyverse, base equivalents exist</li>
<li><em>purrr</em> (note three r&rsquo;s) is pipe (<code>%&gt;%</code>) friendly</li>
<li>Has nice parallelization features.</li>
<li>We&rsquo;ll focus today on <code>map</code> and friends, which is the primary function from the package.</li>
<li>Generally used with lists (for me at least), but can work with any type of vector.</li>
</ul>

<hr />

<h2 id="data">Data</h2>

<p><em>mtcars</em> dataset split by cylinder</p>

<pre><code class="language-r">cyls &lt;- split(mtcars, mtcars$cyl)
str(cyls)
</code></pre>

<pre><code>## List of 3
##  $ 4:'data.frame':	11 obs. of  11 variables:
##   ..$ mpg : num [1:11] 22.8 24.4 22.8 32.4 30.4 33.9 21.5 27.3 26 30.4 ...
##   ..$ cyl : num [1:11] 4 4 4 4 4 4 4 4 4 4 ...
##   ..$ disp: num [1:11] 108 146.7 140.8 78.7 75.7 ...
##   ..$ hp  : num [1:11] 93 62 95 66 52 65 97 66 91 113 ...
##   ..$ drat: num [1:11] 3.85 3.69 3.92 4.08 4.93 4.22 3.7 4.08 4.43 3.77 ...
##   ..$ wt  : num [1:11] 2.32 3.19 3.15 2.2 1.61 ...
##   ..$ qsec: num [1:11] 18.6 20 22.9 19.5 18.5 ...
##   ..$ vs  : num [1:11] 1 1 1 1 1 1 1 1 0 1 ...
##   ..$ am  : num [1:11] 1 0 0 1 1 1 0 1 1 1 ...
##   ..$ gear: num [1:11] 4 4 4 4 4 4 3 4 5 5 ...
##   ..$ carb: num [1:11] 1 2 2 1 2 1 1 1 2 2 ...
##  $ 6:'data.frame':	7 obs. of  11 variables:
##   ..$ mpg : num [1:7] 21 21 21.4 18.1 19.2 17.8 19.7
##   ..$ cyl : num [1:7] 6 6 6 6 6 6 6
##   ..$ disp: num [1:7] 160 160 258 225 168 ...
##   ..$ hp  : num [1:7] 110 110 110 105 123 123 175
##   ..$ drat: num [1:7] 3.9 3.9 3.08 2.76 3.92 3.92 3.62
##   ..$ wt  : num [1:7] 2.62 2.88 3.21 3.46 3.44 ...
##   ..$ qsec: num [1:7] 16.5 17 19.4 20.2 18.3 ...
##   ..$ vs  : num [1:7] 0 0 1 1 1 1 0
##   ..$ am  : num [1:7] 1 1 0 0 0 0 1
##   ..$ gear: num [1:7] 4 4 3 3 4 4 5
##   ..$ carb: num [1:7] 4 4 1 1 4 4 6
##  $ 8:'data.frame':	14 obs. of  11 variables:
##   ..$ mpg : num [1:14] 18.7 14.3 16.4 17.3 15.2 10.4 10.4 14.7 15.5 15.2 ...
##   ..$ cyl : num [1:14] 8 8 8 8 8 8 8 8 8 8 ...
##   ..$ disp: num [1:14] 360 360 276 276 276 ...
##   ..$ hp  : num [1:14] 175 245 180 180 180 205 215 230 150 150 ...
##   ..$ drat: num [1:14] 3.15 3.21 3.07 3.07 3.07 2.93 3 3.23 2.76 3.15 ...
##   ..$ wt  : num [1:14] 3.44 3.57 4.07 3.73 3.78 ...
##   ..$ qsec: num [1:14] 17 15.8 17.4 17.6 18 ...
##   ..$ vs  : num [1:14] 0 0 0 0 0 0 0 0 0 0 ...
##   ..$ am  : num [1:14] 0 0 0 0 0 0 0 0 0 0 ...
##   ..$ gear: num [1:14] 3 3 3 3 3 3 3 3 3 3 ...
##   ..$ carb: num [1:14] 2 4 3 3 3 4 4 4 2 2 ...
</code></pre>

<hr />

<h2 id="map-basic-usage"><code>map</code> basic usage</h2>

<pre><code class="language-r">library(purrr)
map(cyls, ~lm(hp ~ mpg, data = .)) 
</code></pre>

<pre><code>## $`4`
## 
## Call:
## lm(formula = hp ~ mpg, data = .)
## 
## Coefficients:
## (Intercept)          mpg  
##      147.43        -2.43  
## 
## 
## $`6`
## 
## Call:
## lm(formula = hp ~ mpg, data = .)
## 
## Coefficients:
## (Intercept)          mpg  
##     164.156       -2.121  
## 
## 
## $`8`
## 
## Call:
## lm(formula = hp ~ mpg, data = .)
## 
## Coefficients:
## (Intercept)          mpg  
##     294.497       -5.648
</code></pre>

<hr />

<h2 id="basic-usage">Basic usage</h2>

<pre><code class="language-r">map(LIST, FUN, ...)
</code></pre>

<ul>
<li>LIST = list to loop through</li>
<li>FUN = Function to loop through the list</li>
<li>&hellip; Other arguments passed to the function</li>
</ul>

<hr />

<h2 id="different-ways-to-specify-functions">Different ways to specify functions</h2>

<p>The below are equivalent</p>

<pre><code class="language-r">map(cyls, function(x) lm(hp ~ mpg, data = x))
map(cyls, ~lm(hp ~ mpg, data = .)) 
</code></pre>

<p>If we want to extract something from each element of the list, and the that something is named, we can also just supply that name as a string.</p>

<pre><code class="language-r">models &lt;- map(cyls, ~lm(hp ~ mpg, data = .)) 
map(models, &quot;coefficients&quot;)
</code></pre>

<pre><code>## $`4`
## (Intercept)         mpg 
##  147.431465   -2.430092 
## 
## $`6`
## (Intercept)         mpg 
##  164.156412   -2.120802 
## 
## $`8`
## (Intercept)         mpg 
##  294.497384   -5.647887
</code></pre>

<hr />

<h2 id="different-versions-of-map">Different versions of map</h2>

<p>If we call a single function, just list it.</p>

<pre><code class="language-r">lst &lt;- list(first = 1:3, 
			second = 80:100, 
			third = -2:4)

map(lst, mean)
</code></pre>

<pre><code>## $first
## [1] 2
## 
## $second
## [1] 90
## 
## $third
## [1] 1
</code></pre>

<p><code>map</code> will alway return a list. Other variants will return other output.</p>

<pre><code class="language-r">map_df(lst, mean)
</code></pre>

<pre><code>## # A tibble: 1 x 3
##   first second third
##   &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
## 1     2     90     1
</code></pre>

<pre><code class="language-r">map_dbl(lst, mean)
</code></pre>

<pre><code>##  first second  third 
##      2     90      1
</code></pre>

<pre><code class="language-r">map_chr(lst, mean)
</code></pre>

<pre><code>##       first      second       third 
##  &quot;2.000000&quot; &quot;90.000000&quot;  &quot;1.000000&quot;
</code></pre>

<hr />

<h2 id="remember-a-data-frame-is-a-list">Remember, a data frame is a list</h2>

<ul>
<li><p>Loop through all the columns and apply a specific function</p>

<pre><code class="language-r">map_dbl(mtcars, mean)
</code></pre>

<pre><code>##        mpg        cyl       disp         hp       drat         wt 
##  20.090625   6.187500 230.721875 146.687500   3.596563   3.217250 
##       qsec         vs         am       gear       carb 
##  17.848750   0.437500   0.406250   3.687500   2.812500
</code></pre></li>
</ul>

<hr />

<h2 id="putting-them-together">Putting them together</h2>

<pre><code class="language-r">library(tidyverse)
map(cyls, ~lm(hp ~ mpg, data = .)) %&gt;% 
	map_df(coef) %&gt;% 
	mutate(param = c(&quot;intercept&quot;, &quot;slope&quot;)) %&gt;% 
	gather(cyl, val, -4) %&gt;% 
	spread(param, val)
</code></pre>

<pre><code>## # A tibble: 3 x 3
##     cyl intercept     slope
## * &lt;chr&gt;     &lt;dbl&gt;     &lt;dbl&gt;
## 1     4  147.4315 -2.430092
## 2     6  164.1564 -2.120802
## 3     8  294.4974 -5.647887
</code></pre>

<hr />

<h2 id="alternatively-broom">Alternatively: <em>broom</em></h2>

<pre><code class="language-r">library(broom)
map(cyls, ~lm(hp ~ mpg, data = .)) %&gt;% 
	map_df(tidy, .id = &quot;cyl&quot;)
</code></pre>

<pre><code>##   cyl        term   estimate  std.error  statistic     p.value
## 1   4 (Intercept) 147.431465  35.606406  4.1405882 0.002519431
## 2   4         mpg  -2.430092   1.318359 -1.8432709 0.098398581
## 3   6 (Intercept) 164.156412 146.508014  1.1204603 0.313430721
## 4   6         mpg  -2.120802   7.403631 -0.2864543 0.786020206
## 5   8 (Intercept) 294.497384  84.337195  3.4919040 0.004447715
## 6   8         mpg  -5.647887   5.512168 -1.0246218 0.325753780
</code></pre>

<hr />

<h2 id="more-complex-versions-of-map">More complex versions of <code>map</code></h2>

<ul>
<li><code>map2</code> iterates over two lists/vectors in parallel</li>
<li><code>pmap</code> iterates over <em>p</em> lists/vectors in parallel</li>
</ul>

<h1 id="calculate-differences-in-means">Calculate differences in means</h1>

<p>(spacing added just for clarity)</p>

<pre><code class="language-r">set.seed(222)
map2(list(rnorm(100), 
		  rnorm(100),
		  rnorm(100)),

	 list(rnorm(100, 0.5), 
	 	  rnorm(100, 1), 
	 	  rnorm(100, 0.2)), 

	~mean(.x) - mean(.y))
</code></pre>

<pre><code>## [[1]]
## [1] -0.5997455
## 
## [[2]]
## [1] -1.083101
## 
## [[3]]
## [1] -0.2517111
</code></pre>

<hr />

<h2 id="calculate-effect-sizes">Calculate effect sizes</h2>

<pre><code class="language-r">set.seed(222)
map2_dbl(list(rnorm(100), 
		  	  rnorm(100),
		  	  rnorm(100)),

	 	 list(rnorm(100, 0.5), 
	 	  	  rnorm(100, 1), 
	 	  	  rnorm(100, 0.2)),

	~ (mean(.x) - mean(.y)) / sqrt(
		((length(.x) - 1) * var(.x) +  (length(.y) - 1) * var(.y)) /
					 ((length(.x) + length(.y)) - 2)))
</code></pre>

<pre><code>## [1] -0.6125145 -1.0812928 -0.2446314
</code></pre>

<hr />

<h2 id="pmap"><code>pmap</code></h2>

<ul>
<li>We won&rsquo;t focus on <code>pmap</code> today, but it&rsquo;s worth noting that the syntax is slightly different. You supply one (possibly nested) list with all the arguments to the function, and then supply the function.</li>
</ul>

<p>For example, setup a simulation with different sample sizes, means, and standard deviations. (In this particular example we could )</p>

<pre><code class="language-r">n &lt;- list(50, 100, 250, 500)
mu &lt;- list(10, 15, 10, 15)
stdev &lt;- list(1, 1, 2, 2)

sim_data &lt;- pmap(list(n, mu, stdev), rnorm)
str(sim_data)
</code></pre>

<pre><code>## List of 4
##  $ : num [1:50] 10.06 10.2 10.39 9.67 10.75 ...
##  $ : num [1:100] 15.1 16.5 17.2 14.4 15.2 ...
##  $ : num [1:250] 8.04 7.37 8.17 10.49 11.96 ...
##  $ : num [1:500] 15.4 15.7 15 18.4 17.8 ...
</code></pre>

<hr />

<h2 id="use-map-to-check-simulation">Use <code>map</code> to check simulation</h2>

<ul>
<li><em>sim_data</em> is a list, so we can loop through it</li>

<li><p>We saw on the previous slide that the sample sizes were correct. What about the means and standard deviations?</p>

<pre><code class="language-r">map_dbl(sim_data, mean)
</code></pre>

<pre><code>## [1] 10.045945 15.062124  9.768937 14.980899
</code></pre>

<pre><code class="language-r">map_dbl(sim_data, sd)
</code></pre>

<pre><code>## [1] 0.7623378 0.9640901 2.0434633 2.0012167
</code></pre></li>
</ul>

<hr />

<h2 id="another-pmap-example">Another <code>pmap</code> example</h2>

<p>(could do this while avoiding the loop altogether)</p>

<pre><code class="language-r">pmap_chr(list(rep(1:10, 2), 
		  letters[1:20], 
		  rep(c(&quot;control&quot;, &quot;treatment&quot;), each = 10)), 
	paste, sep = &quot;-&quot;)
</code></pre>

<pre><code>##  [1] &quot;1-a-control&quot;    &quot;2-b-control&quot;    &quot;3-c-control&quot;    &quot;4-d-control&quot;   
##  [5] &quot;5-e-control&quot;    &quot;6-f-control&quot;    &quot;7-g-control&quot;    &quot;8-h-control&quot;   
##  [9] &quot;9-i-control&quot;    &quot;10-j-control&quot;   &quot;1-k-treatment&quot;  &quot;2-l-treatment&quot; 
## [13] &quot;3-m-treatment&quot;  &quot;4-n-treatment&quot;  &quot;5-o-treatment&quot;  &quot;6-p-treatment&quot; 
## [17] &quot;7-q-treatment&quot;  &quot;8-r-treatment&quot;  &quot;9-s-treatment&quot;  &quot;10-t-treatment&quot;
</code></pre>

<hr />

<h2 id="nesting-data-frames">Nesting data frames</h2>

<p>Rather than splitting data frames (as we did before), it can often be helpful to <code>nest()</code> them instead. The reason you would want to nest a data frame is for similar reasons to wanting to split it.</p>

<p>For example,</p>

<pre><code class="language-r">nested &lt;- mtcars %&gt;% 
	group_by(cyl) %&gt;% 
	nest()
nested
</code></pre>

<pre><code>## # A tibble: 3 x 2
##     cyl               data
##   &lt;dbl&gt;             &lt;list&gt;
## 1     6  &lt;tibble [7 x 10]&gt;
## 2     4 &lt;tibble [11 x 10]&gt;
## 3     8 &lt;tibble [14 x 10]&gt;
</code></pre>

<hr />

<h2 id="list-columns">List columns</h2>

<p>In the previous example:
* Data are split by cylinder, just as before
* The list of data are then stored into a list column in a data frame
* Each &ldquo;cell&rdquo; in the list column contains all the data for that corresponding
  row in the data frame (cylinder).
* In some ways this is a bit odd, but it can help us stay organized.</p>

<hr />

<pre><code class="language-r">nested$data
</code></pre>

<pre><code>## [[1]]
## # A tibble: 7 x 10
##     mpg  disp    hp  drat    wt  qsec    vs    am  gear  carb
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  21.0 160.0   110  3.90 2.620 16.46     0     1     4     4
## 2  21.0 160.0   110  3.90 2.875 17.02     0     1     4     4
## 3  21.4 258.0   110  3.08 3.215 19.44     1     0     3     1
## 4  18.1 225.0   105  2.76 3.460 20.22     1     0     3     1
## 5  19.2 167.6   123  3.92 3.440 18.30     1     0     4     4
## 6  17.8 167.6   123  3.92 3.440 18.90     1     0     4     4
## 7  19.7 145.0   175  3.62 2.770 15.50     0     1     5     6
## 
## [[2]]
## # A tibble: 11 x 10
##      mpg  disp    hp  drat    wt  qsec    vs    am  gear  carb
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  22.8 108.0    93  3.85 2.320 18.61     1     1     4     1
##  2  24.4 146.7    62  3.69 3.190 20.00     1     0     4     2
##  3  22.8 140.8    95  3.92 3.150 22.90     1     0     4     2
##  4  32.4  78.7    66  4.08 2.200 19.47     1     1     4     1
##  5  30.4  75.7    52  4.93 1.615 18.52     1     1     4     2
##  6  33.9  71.1    65  4.22 1.835 19.90     1     1     4     1
##  7  21.5 120.1    97  3.70 2.465 20.01     1     0     3     1
##  8  27.3  79.0    66  4.08 1.935 18.90     1     1     4     1
##  9  26.0 120.3    91  4.43 2.140 16.70     0     1     5     2
## 10  30.4  95.1   113  3.77 1.513 16.90     1     1     5     2
## 11  21.4 121.0   109  4.11 2.780 18.60     1     1     4     2
## 
## [[3]]
## # A tibble: 14 x 10
##      mpg  disp    hp  drat    wt  qsec    vs    am  gear  carb
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  18.7 360.0   175  3.15 3.440 17.02     0     0     3     2
##  2  14.3 360.0   245  3.21 3.570 15.84     0     0     3     4
##  3  16.4 275.8   180  3.07 4.070 17.40     0     0     3     3
##  4  17.3 275.8   180  3.07 3.730 17.60     0     0     3     3
##  5  15.2 275.8   180  3.07 3.780 18.00     0     0     3     3
##  6  10.4 472.0   205  2.93 5.250 17.98     0     0     3     4
##  7  10.4 460.0   215  3.00 5.424 17.82     0     0     3     4
##  8  14.7 440.0   230  3.23 5.345 17.42     0     0     3     4
##  9  15.5 318.0   150  2.76 3.520 16.87     0     0     3     2
## 10  15.2 304.0   150  3.15 3.435 17.30     0     0     3     2
## 11  13.3 350.0   245  3.73 3.840 15.41     0     0     3     4
## 12  19.2 400.0   175  3.08 3.845 17.05     0     0     3     2
## 13  15.8 351.0   264  4.22 3.170 14.50     0     1     5     4
## 14  15.0 301.0   335  3.54 3.570 14.60     0     1     5     8
</code></pre>

<hr />

<h2 id="fit-multiple-models">Fit multiple models</h2>

<pre><code class="language-r">nested &lt;- nested %&gt;% 
	mutate(m1_mpg = map(data, ~lm(hp ~ mpg, data = .)),
		   m2_mpg_disp = map(data, ~lm(hp ~ mpg + disp, data = .)))
nested
</code></pre>

<pre><code>## # A tibble: 3 x 4
##     cyl               data   m1_mpg m2_mpg_disp
##   &lt;dbl&gt;             &lt;list&gt;   &lt;list&gt;      &lt;list&gt;
## 1     6  &lt;tibble [7 x 10]&gt; &lt;S3: lm&gt;    &lt;S3: lm&gt;
## 2     4 &lt;tibble [11 x 10]&gt; &lt;S3: lm&gt;    &lt;S3: lm&gt;
## 3     8 &lt;tibble [14 x 10]&gt; &lt;S3: lm&gt;    &lt;S3: lm&gt;
</code></pre>

<hr />

<h2 id="see-models-for-mpg-and-disp">See models for <em>mpg</em> and <em>disp</em></h2>

<pre><code class="language-r">nested$m2_mpg_disp
</code></pre>

<pre><code>## [[1]]
## 
## Call:
## lm(formula = hp ~ mpg + disp, data = .)
## 
## Coefficients:
## (Intercept)          mpg         disp  
##    201.1055      -1.2504      -0.2953  
## 
## 
## [[2]]
## 
## Call:
## lm(formula = hp ~ mpg + disp, data = .)
## 
## Coefficients:
## (Intercept)          mpg         disp  
##   140.68630     -2.29124      0.02894  
## 
## 
## [[3]]
## 
## Call:
## lm(formula = hp ~ mpg + disp, data = .)
## 
## Coefficients:
## (Intercept)          mpg         disp  
##   311.35825     -6.06153     -0.03006
</code></pre>

<hr />

<h2 id="summary-of-models-for-mpg-and-disp">Summary of models for <em>mpg</em> and <em>disp</em></h2>

<pre><code class="language-r">map(nested$m2_mpg_disp, summary)
</code></pre>

<pre><code>## [[1]]
## 
## Call:
## lm(formula = hp ~ mpg + disp, data = .)
## 
## Residuals:
##       1       2       3       4       5       6       7 
## -17.599 -17.599  11.841  -7.030  -4.605  -6.356  41.346 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 201.1055   144.6027   1.391    0.237
## mpg          -1.2504     7.1714  -0.174    0.870
## disp         -0.2953     0.2508  -1.177    0.304
## 
## Residual standard error: 25.4 on 4 degrees of freedom
## Multiple R-squared:  0.2694,	Adjusted R-squared:  -0.09595 
## F-statistic: 0.7374 on 2 and 4 DF,  p-value: 0.5338
## 
## 
## [[2]]
## 
## Call:
## lm(formula = hp ~ mpg + disp, data = .)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -27.026  -8.575   1.428   4.442  39.215 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 140.68630   99.64213   1.412    0.196
## mpg          -2.29124    2.35746  -0.972    0.360
## disp          0.02894    0.39565   0.073    0.943
## 
## Residual standard error: 19.94 on 8 degrees of freedom
## Multiple R-squared:  0.2745,	Adjusted R-squared:  0.09318 
## F-statistic: 1.514 on 2 and 8 DF,  p-value: 0.277
## 
## 
## [[3]]
## 
## Call:
## lm(formula = hp ~ mpg + disp, data = .)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -60.08 -27.76 -15.19  23.83 123.61 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept) 311.35825  167.65969   1.857   0.0903 .
## mpg          -6.06153    6.73483  -0.900   0.3874  
## disp         -0.03006    0.25441  -0.118   0.9081  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 53.11 on 11 degrees of freedom
## Multiple R-squared:  0.08161,	Adjusted R-squared:  -0.08536 
## F-statistic: 0.4888 on 2 and 11 DF,  p-value: 0.6261
</code></pre>

<hr />

<h2 id="for-the-averse">For the <code>$</code> averse</h2>

<pre><code class="language-r">nested %&gt;% 
	transmute(smry = map(m2_mpg_disp, summary)) %&gt;% 
	flatten()
</code></pre>

<pre><code>## [[1]]
## 
## Call:
## lm(formula = hp ~ mpg + disp, data = .)
## 
## Residuals:
##       1       2       3       4       5       6       7 
## -17.599 -17.599  11.841  -7.030  -4.605  -6.356  41.346 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 201.1055   144.6027   1.391    0.237
## mpg          -1.2504     7.1714  -0.174    0.870
## disp         -0.2953     0.2508  -1.177    0.304
## 
## Residual standard error: 25.4 on 4 degrees of freedom
## Multiple R-squared:  0.2694,	Adjusted R-squared:  -0.09595 
## F-statistic: 0.7374 on 2 and 4 DF,  p-value: 0.5338
## 
## 
## [[2]]
## 
## Call:
## lm(formula = hp ~ mpg + disp, data = .)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -27.026  -8.575   1.428   4.442  39.215 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 140.68630   99.64213   1.412    0.196
## mpg          -2.29124    2.35746  -0.972    0.360
## disp          0.02894    0.39565   0.073    0.943
## 
## Residual standard error: 19.94 on 8 degrees of freedom
## Multiple R-squared:  0.2745,	Adjusted R-squared:  0.09318 
## F-statistic: 1.514 on 2 and 8 DF,  p-value: 0.277
## 
## 
## [[3]]
## 
## Call:
## lm(formula = hp ~ mpg + disp, data = .)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -60.08 -27.76 -15.19  23.83 123.61 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept) 311.35825  167.65969   1.857   0.0903 .
## mpg          -6.06153    6.73483  -0.900   0.3874  
## disp         -0.03006    0.25441  -0.118   0.9081  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 53.11 on 11 degrees of freedom
## Multiple R-squared:  0.08161,	Adjusted R-squared:  -0.08536 
## F-statistic: 0.4888 on 2 and 11 DF,  p-value: 0.6261
</code></pre>

<hr />

<h2 id="compare-models">Compare Models</h2>

<pre><code class="language-r">nested &lt;- nested %&gt;% 
	mutate(m12_comp = map2(m1_mpg, m2_mpg_disp, anova), 
		   p = map(m12_comp, &quot;Pr(&gt;F)&quot;),
		   p = map_dbl(p, `[`, 2))
nested
</code></pre>

<pre><code>## # A tibble: 3 x 6
##     cyl               data   m1_mpg m2_mpg_disp        m12_comp         p
##   &lt;dbl&gt;             &lt;list&gt;   &lt;list&gt;      &lt;list&gt;          &lt;list&gt;     &lt;dbl&gt;
## 1     6  &lt;tibble [7 x 10]&gt; &lt;S3: lm&gt;    &lt;S3: lm&gt; &lt;anova [2 x 6]&gt; 0.3043020
## 2     4 &lt;tibble [11 x 10]&gt; &lt;S3: lm&gt;    &lt;S3: lm&gt; &lt;anova [2 x 6]&gt; 0.9434844
## 3     8 &lt;tibble [14 x 10]&gt; &lt;S3: lm&gt;    &lt;S3: lm&gt; &lt;anova [2 x 6]&gt; 0.9080672
</code></pre>

<hr />

<h2 id="extract-all-coefficients">Extract all coefficients</h2>

<pre><code class="language-r">coefs &lt;- nested %&gt;% 
	select(3:4) %&gt;% 
	map(map_df, tidy) %&gt;% 
	map_df(bind_rows, .id = &quot;model&quot;)
coefs
</code></pre>

<pre><code>##          model        term     estimate   std.error   statistic
## 1       m1_mpg (Intercept) 164.15641199 146.5080145  1.12046029
## 2       m1_mpg         mpg  -2.12080234   7.4036315 -0.28645434
## 3       m1_mpg (Intercept) 147.43146466  35.6064062  4.14058818
## 4       m1_mpg         mpg  -2.43009244   1.3183588 -1.84327091
## 5       m1_mpg (Intercept) 294.49738431  84.3371946  3.49190397
## 6       m1_mpg         mpg  -5.64788732   5.5121677 -1.02462183
## 7  m2_mpg_disp (Intercept) 201.10545950 144.6026821  1.39074502
## 8  m2_mpg_disp         mpg  -1.25040042   7.1713987 -0.17435935
## 9  m2_mpg_disp        disp  -0.29530305   0.2508059 -1.17741686
## 10 m2_mpg_disp (Intercept) 140.68630194  99.6421350  1.41191577
## 11 m2_mpg_disp         mpg  -2.29123552   2.3574552 -0.97191054
## 12 m2_mpg_disp        disp   0.02894082   0.3956489  0.07314773
## 13 m2_mpg_disp (Intercept) 311.35824930 167.6596917  1.85708471
## 14 m2_mpg_disp         mpg  -6.06152869   6.7348316 -0.90002676
## 15 m2_mpg_disp        disp  -0.03006197   0.2544069 -0.11816490
##        p.value
## 1  0.313430721
## 2  0.786020206
## 3  0.002519431
## 4  0.098398581
## 5  0.004447715
## 6  0.325753780
## 7  0.236675952
## 8  0.870052170
## 9  0.304302032
## 10 0.195667537
## 11 0.359560194
## 12 0.943484382
## 13 0.090255904
## 14 0.387385396
## 15 0.908067161
</code></pre>

<hr />

<h2 id="next-steps">Next steps</h2>

<p>From here we could go on to plotting, etc., instead, let&rsquo;s look at a full, applied example that uses some of these topics.</p>

<h1 id="context">Context</h1>

<ul>
<li>Evaluating intervention response through &ldquo;checkpoints&rdquo;</li>
<li>Only concerning if students do not receive full credit at each checkpoint</li>
<li>Evaluate patterns of checkpoint response to see if we can identify different types of non-responders</li>
</ul>

<h1 id="analysis">Analysis</h1>

<ul>
<li>Examine means at pre- and post-test on various measures of mathematics for student groups (according to their patterns of response)</li>
<li>Examine residual gains by groups</li>
</ul>

  </div>
</article>
        </div>
        
  <div id="disqus_thread"></div>
    <script type="text/javascript">
    (function() {
      
      
      if (window.location.hostname === 'localhost') return;

      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      var disqus_shortname = 'http-www-dandersondata-com';
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

  

  
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="social-links">
      <a href="mailto:daniela@uoregon.edu" class="iconfont icon-email" title="email"></a>
      <a href="https://stackoverflow.com/users/4959854/daniel-anderson" class="iconfont icon-stack-overflow" title="stack-overflow"></a>
      <a href="https://twitter.com/datalorax_" class="iconfont icon-twitter" title="twitter"></a>
      <a href="https://github.com/datalorax" class="iconfont icon-github" title="github"></a>
  <a href="/index.xml" type="application/rss+xml" class="iconfont icon-rss" title="rss"></a>
</div>

<div class="copyright">
  <span class="power-by">
    Powered by <a class="hexo-link" href="https://gohugo.io">Hugo</a>
  </span>
  <span class="division">|</span>
  <span class="theme-info">
    Theme based on 
    <a class="theme-link" href="https://github.com/olOwOlo/hugo-theme-even">Even</a>
  </span>

  

  <span class="copyright-year">
    &copy; 
    
      2017 - 
    2019
    <span class="author">Daniel Anderson</span>
  </span>
</div>
    </footer>

    <div class="back-to-top" id="back-to-top">
      <i class="iconfont icon-up"></i>
    </div>
  </div>
  
<script src="/lib/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<script type="text/javascript" src="/lib/jquery/jquery-3.2.1.min.js"></script>
  <script type="text/javascript" src="/lib/slideout/slideout-1.0.1.min.js"></script>
  <script type="text/javascript" src="/lib/fancybox/jquery.fancybox-3.1.20.min.js"></script>
<script type="text/javascript" src="/dist/even.min.js?v=3.0.1"></script>
  <script type="text/javascript">
    window.MathJax = {
      tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]},
      showProcessingMessages: false,
      messageStyle: 'none'
    };
  </script>
  <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"></script>








</body>
</html>
