<!DOCTYPE HTML>

<html>
	<head>
	<meta name="generator" content="Hugo 0.24.1" />
		<title>data science in education</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="/css/main.css" />
		<link rel="stylesheet" href="/css/project.css" />
		
		<noscript><link rel="stylesheet" href="/css/noscript.css" /></noscript>
	</head>
	
			<script src="/js/jquery.min.js"></script>
	<body>

    
      <div id="wrapper">

        
          <header id="header">
            <div class="logo">
              
                        
              <span class="icon fa-code"></span>
            
            </div>
            <div class="content">
              <div class="inner">
                <h1>data science in education</h1>
                <p><!--[-->a blog by daniel anderson<!--]--><br /></p>
              </div>
            </div>
            <nav>
              <ul>
                
                  <li><a href="#work">Work</a></li>
                
                  <li><a href="#about">About</a></li>
                
                  <li><a href="#elements">Elements</a></li>
                
                  <li><a href="#2017-11-02-trial2">esvis</a></li>
                
                  <li><a href="#2017-11-02-trial">trial</a></li>
                
                  <li><a href="#2015-07-23-r-rmarkdown">Hello R Markdown</a></li>
                
              </ul>
            </nav>
          </header>

        
          <div id="main">
            
              <article id="work">
  <h1>Work</h1>
  <p>I work as a Research Associate at Behavioral Research and Teaching (BRT), a
grant-based center at the University of Oregon. You can see our website <a href="http://www.brtprojects.org">here</a></p>


<figure class="image main">
    
        <img src="/images/lokey.jpg" />
    
    
</figure>


</article>

            
              <article id="about">
  <h1>About</h1>
  <p>This blog relates to a lot of my work with data - some of which is directly related to my job and some of which is not. I enjoy programming with R, and all my blog posts here are related to my work with R.</p>


<figure class="image main">
    
        <img src="/images/scatter.png" />
    
    
</figure>


</article>

            
              <article id="elements">
  <h1>Elements</h1>
  

<h3 class="major">Hugo shortcodes in theme</h3>

<p><code>{&zwnj;{&lt; socialLinks &gt;}}</code> will get into <ul class="icons">

	<li><a href="https://twitter.com/DJAnderson_07" class="icon fa-twitter"><span class="label">twitter</span></a></li>

	<li><a href="https://stackoverflow.com/users/4959854/daniel-anderson" class="icon fa-stackoverflow"><span class="label">stackoverflow</span></a></li>

	<li><a href="https://github.com/DJAnderson07" class="icon fa-github"><span class="label">github</span></a></li>

</ul> configured in <code>config.toml</code>.</p>

<p><code>{&zwnj;{&lt; gmaps  pb=&rdquo;&lt;sharecode&gt;&rdquo; &gt;}}</code> will get a google map
<iframe src="https://www.google.com/maps/embed?pb=%211m18%211m12%211m3%211d86456.59681285016%212d8.466675323953403%213d47.377433669132884%212m3%211f0%212f0%213f0%213m2%211i1024%212i768%214f13.1%213m3%211m2%211s0x47900b9749bea219%253A0xe66e8df1e71fdc03%212zWsO8cmljaA%215e0%213m2%211sde%212sch%214v1488248947910" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe></p>

<p>To get the pb parameter value, search the desired place on google maps and click the share button and copy/paste the pb parameter out of the iframe code.</p>

<h3 class="major">Text</h3>

<p>This is <strong>bold</strong> and this is <strong>strong</strong>. This is <em>italic</em> and this is <em>emphasized</em>.
This is <sup>superscript</sup> text and this is <sub>subscript</sub> text.
This is <u>underlined</u> and this is code: <code>for (;;) { &hellip; }</code>.
Finally, <a href="https://beegit.com/markdown-cheat-sheet">this is a link to a markdown cheatsheet</a>.</p>

<blockquote>
<p>Not all markdown syntax is allowed but you can mix most html tags into the markdown text.</p>
</blockquote>

<hr />

<h2 id="heading-level-2">Heading Level 2</h2>

<h3 id="heading-level-3">Heading Level 3</h3>

<h4 id="heading-level-4">Heading Level 4</h4>

<h5 id="heading-level-5">Heading Level 5</h5>

<h6 id="heading-level-6">Heading Level 6</h6>

<hr />

<h4 id="blockquote">Blockquote</h4>

<blockquote>
<p>Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan faucibus. Vestibulum ante ipsum primis in faucibus lorem ipsum dolor sit amet nullam adipiscing eu felis.</p>
</blockquote>

<h4 id="preformatted">Preformatted</h4>

<pre><code>i = 0;

while (!deck.isInOrder()) {
    print 'Iteration ' + i;
    deck.shuffle();
    i++;
}

print 'It took ' + i + ' iterations to sort the deck.';
</code></pre>

<h3 class="major">Lists</h3>

<h4 id="unordered">Unordered</h4>

<ul>
<li>Dolor pulvinar etiam.</li>
<li>Sagittis adipiscing.</li>
<li>Felis enim feugiat.</li>
</ul>

<h4 id="ordered">Ordered</h4>

<ol>
<li>Dolor pulvinar etiam.</li>
<li>Etiam vel felis viverra.</li>
<li>Felis enim feugiat.</li>
<li>Dolor pulvinar etiam.</li>
<li>Etiam vel felis lorem.</li>
<li>Felis enim et feugiat.</li>
</ol>

<h4 id="icons">Icons</h4>

<ul class="icons">
    <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
    <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
    <li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
    <li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
</ul>

<h4 id="actions">Actions</h4>

<ul class="actions">
    <li><a href="#" class="button special">Default</a></li>
    <li><a href="#" class="button">Default</a></li>
</ul>
<ul class="actions vertical">
    <li><a href="#" class="button special">Default</a></li>
    <li><a href="#" class="button">Default</a></li>
</ul>
                                

<p><h3 class="major">Table</h3></p>

<h4 id="default">Default</h4>

<table>
<thead>
<tr>
<th>Tables</th>
<th align="center">Are</th>
<th align="right">Cool</th>
</tr>
</thead>

<tbody>
<tr>
<td>col 3 is</td>
<td align="center">right-aligned</td>
<td align="right">$1600</td>
</tr>

<tr>
<td>col 2 is</td>
<td align="center">centered</td>
<td align="right">$12</td>
</tr>

<tr>
<td>zebra stripes</td>
<td align="center">are neat</td>
<td align="right">$1</td>
</tr>
</tbody>
</table>

<div class="table-wrapper">
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Item One</td>
                <td>Ante turpis integer aliquet porttitor.</td>
                <td>29.99</td>
            </tr>
            <tr>
                <td>Item Two</td>
                <td>Vis ac commodo adipiscing arcu aliquet.</td>
                <td>19.99</td>
            </tr>
            <tr>
                <td>Item Three</td>
                <td> Morbi faucibus arcu accumsan lorem.</td>
                <td>29.99</td>
            </tr>
            <tr>
                <td>Item Four</td>
                <td>Vitae integer tempus condimentum.</td>
                <td>19.99</td>
            </tr>
            <tr>
                <td>Item Five</td>
                <td>Ante turpis integer aliquet porttitor.</td>
                <td>29.99</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2"></td>
                <td>100.00</td>
            </tr>
        </tfoot>
    </table>
</div>

<p><h4>Alternate</h4>
<div class="table-wrapper">
    <table class="alt">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Item One</td>
                <td>Ante turpis integer aliquet porttitor.</td>
                <td>29.99</td>
            </tr>
            <tr>
                <td>Item Two</td>
                <td>Vis ac commodo adipiscing arcu aliquet.</td>
                <td>19.99</td>
            </tr>
            <tr>
                <td>Item Three</td>
                <td> Morbi faucibus arcu accumsan lorem.</td>
                <td>29.99</td>
            </tr>
            <tr>
                <td>Item Four</td>
                <td>Vitae integer tempus condimentum.</td>
                <td>19.99</td>
            </tr>
            <tr>
                <td>Item Five</td>
                <td>Ante turpis integer aliquet porttitor.</td>
                <td>29.99</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2"></td>
                <td>100.00</td>
            </tr>
        </tfoot>
    </table>
</div></p>

<p><h3 class="major">Buttons</h3>
<ul class="actions">
    <li><a href="#" class="button special">Special</a></li>
    <li><a href="#" class="button">Default</a></li>
</ul>
<ul class="actions">
    <li><a href="#" class="button">Default</a></li>
    <li><a href="#" class="button small">Small</a></li>
</ul>
<ul class="actions">
    <li><a href="#" class="button special icon fa-download">Icon</a></li>
    <li><a href="#" class="button icon fa-download">Icon</a></li>
</ul>
<ul class="actions">
    <li><span class="button special disabled">Disabled</span></li>
    <li><span class="button disabled">Disabled</span></li>
</ul></p>

<p><h3 class="major">Form</h3>
<form method="post" action="#">
    <div class="field half first">
        <label for="demo-name">Name</label>
        <input type="text" name="demo-name" id="demo-name" value="" placeholder="Jane Doe" />
    </div>
    <div class="field half">
        <label for="demo-email">Email</label>
        <input type="email" name="demo-email" id="demo-email" value="" placeholder="jane@untitled.tld" />
    </div>
    <div class="field">
        <label for="demo-category">Category</label>
        <div class="select-wrapper">
            <select name="demo-category" id="demo-category">
                <option value="">-</option>
                <option value="1">Manufacturing</option>
                <option value="1">Shipping</option>
                <option value="1">Administration</option>
                <option value="1">Human Resources</option>
            </select>
        </div>
    </div>
    <div class="field half first">
        <input type="radio" id="demo-priority-low" name="demo-priority" checked>
        <label for="demo-priority-low">Low</label>
    </div>
    <div class="field half">
        <input type="radio" id="demo-priority-high" name="demo-priority">
        <label for="demo-priority-high">High</label>
    </div>
    <div class="field half first">
        <input type="checkbox" id="demo-copy" name="demo-copy">
        <label for="demo-copy">Email me a copy</label>
    </div>
    <div class="field half">
        <input type="checkbox" id="demo-human" name="demo-human" checked>
        <label for="demo-human">Not a robot</label>
    </div>
    <div class="field">
        <label for="demo-message">Message</label>
        <textarea name="demo-message" id="demo-message" placeholder="Enter your message" rows="6"></textarea>
    </div>
    <ul class="actions">
        <li><input type="submit" value="Send Message" class="special" /></li>
        <li><input type="reset" value="Reset" /></li>
    </ul>
</form></p>

</article>

            
              <article id="2017-11-02-trial2">
  <h1>esvis</h1>
  <p>Here’s some more stuff, this time with my <em>esvsis</em> package.</p>
<p>Here’s a sampling of the data we’ll be playing with.</p>
<pre class="r"><code>library(esvis)
knitr::kable(head(benchmarks))</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">sid</th>
<th align="right">cohort</th>
<th align="left">sped</th>
<th align="left">ethnicity</th>
<th align="left">frl</th>
<th align="left">ell</th>
<th align="left">season</th>
<th align="right">reading</th>
<th align="right">math</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">332347</td>
<td align="right">1</td>
<td align="left">Non-Sped</td>
<td align="left">Native Am.</td>
<td align="left">Non-FRL</td>
<td align="left">Non-ELL</td>
<td align="left">Winter</td>
<td align="right">208</td>
<td align="right">205</td>
</tr>
<tr class="even">
<td align="right">400047</td>
<td align="right">1</td>
<td align="left">Non-Sped</td>
<td align="left">Native Am.</td>
<td align="left">FRL</td>
<td align="left">Non-ELL</td>
<td align="left">Spring</td>
<td align="right">212</td>
<td align="right">218</td>
</tr>
<tr class="odd">
<td align="right">402107</td>
<td align="right">1</td>
<td align="left">Non-Sped</td>
<td align="left">White</td>
<td align="left">Non-FRL</td>
<td align="left">Non-ELL</td>
<td align="left">Winter</td>
<td align="right">201</td>
<td align="right">212</td>
</tr>
<tr class="even">
<td align="right">402547</td>
<td align="right">1</td>
<td align="left">Non-Sped</td>
<td align="left">White</td>
<td align="left">Non-FRL</td>
<td align="left">Non-ELL</td>
<td align="left">Fall</td>
<td align="right">185</td>
<td align="right">177</td>
</tr>
<tr class="odd">
<td align="right">403047</td>
<td align="right">1</td>
<td align="left">Sped</td>
<td align="left">Hispanic</td>
<td align="left">FRL</td>
<td align="left">Active</td>
<td align="left">Winter</td>
<td align="right">179</td>
<td align="right">192</td>
</tr>
<tr class="even">
<td align="right">403307</td>
<td align="right">1</td>
<td align="left">Sped</td>
<td align="left">Hispanic</td>
<td align="left">Non-FRL</td>
<td align="left">Non-ELL</td>
<td align="left">Winter</td>
<td align="right">189</td>
<td align="right">188</td>
</tr>
</tbody>
</table>
<p>Here’s a probability-probability plot for English learners in reading.</p>
<pre class="r"><code>pp_plot(reading ~ ell, benchmarks)</code></pre>
<p><img src="/post/2017-11-02-trial2_files/figure-html/esvis-1.png" width="672" /></p>
<p>There’s customizable themes too. Here’ the built in dark theme.</p>
<pre class="r"><code>pp_plot(reading ~ ell, benchmarks, theme = &quot;dark&quot;)</code></pre>
<p><img src="/post/2017-11-02-trial2_files/figure-html/esvis_dark-1.png" width="672" /></p>
<p>We can also look at binned effect size plots for a similar view of the data, but this time with Cohen’s d. Let’s look at it by quintile, and we’ll use the tan theme this time.</p>
<pre class="r"><code>binned_plot(reading ~ ell, 
            data = benchmarks, 
            qtiles = seq(0, 1, 0.2),
            theme = &quot;tan&quot;)</code></pre>
<p><img src="/post/2017-11-02-trial2_files/figure-html/binned_quintile-1.png" width="672" /></p>
<p>Okay. That’s good enough for now.</p>

</article>

            
              <article id="2017-11-02-trial">
  <h1>trial</h1>
  <p>Here’s some stuff</p>
<pre class="r"><code>library(ggplot2)
ggplot(diamonds, aes(carat, price)) +
  geom_point(color = &quot;gray80&quot;) +
  geom_smooth(aes(color = clarity)) +
  ggthemes::theme_calc()</code></pre>
<p><img src="/post/2017-11-02-trial_files/figure-html/plot-1.png" width="672" /></p>
<p>here’s the head of the dataset</p>
<pre class="r"><code>head(diamonds)</code></pre>
<pre><code>## # A tibble: 6 x 10
##   carat       cut color clarity depth table price     x     y     z
##   &lt;dbl&gt;     &lt;ord&gt; &lt;ord&gt;   &lt;ord&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1  0.23     Ideal     E     SI2  61.5    55   326  3.95  3.98  2.43
## 2  0.21   Premium     E     SI1  59.8    61   326  3.89  3.84  2.31
## 3  0.23      Good     E     VS1  56.9    65   327  4.05  4.07  2.31
## 4  0.29   Premium     I     VS2  62.4    58   334  4.20  4.23  2.63
## 5  0.31      Good     J     SI2  63.3    58   335  4.34  4.35  2.75
## 6  0.24 Very Good     J    VVS2  62.8    57   336  3.94  3.96  2.48</code></pre>

</article>

            
              <article id="2015-07-23-r-rmarkdown">
  <h1>Hello R Markdown</h1>
  <div id="r-markdown" class="section level1">
<h1>R Markdown</h1>
<p>This is an R Markdown document. Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. For more details on using R Markdown see <a href="http://rmarkdown.rstudio.com" class="uri">http://rmarkdown.rstudio.com</a>.</p>
<p>You can embed an R code chunk like this:</p>
<pre class="r"><code>summary(cars)
##      speed           dist       
##  Min.   : 4.0   Min.   :  2.00  
##  1st Qu.:12.0   1st Qu.: 26.00  
##  Median :15.0   Median : 36.00  
##  Mean   :15.4   Mean   : 42.98  
##  3rd Qu.:19.0   3rd Qu.: 56.00  
##  Max.   :25.0   Max.   :120.00
fit &lt;- lm(dist ~ speed, data = cars)
fit
## 
## Call:
## lm(formula = dist ~ speed, data = cars)
## 
## Coefficients:
## (Intercept)        speed  
##     -17.579        3.932</code></pre>
</div>
<div id="including-plots" class="section level1">
<h1>Including Plots</h1>
<p>You can also embed plots. See Figure <a href="#fig:pie">1</a> for example:</p>
<pre class="r"><code>par(mar = c(0, 1, 0, 1))
pie(
  c(280, 60, 20),
  c(&#39;Sky&#39;, &#39;Sunny side of pyramid&#39;, &#39;Shady side of pyramid&#39;),
  col = c(&#39;#0292D8&#39;, &#39;#F7EA39&#39;, &#39;#C4B632&#39;),
  init.angle = -50, border = NA
)</code></pre>
<div class="figure"><span id="fig:pie"></span>
<img src="/post/2015-07-23-r-rmarkdown_files/figure-html/pie-1.png" alt="A fancy pie chart." width="672" />
<p class="caption">
Figure 1: A fancy pie chart.
</p>
</div>
</div>

</article>

            
          </div>

        
          <div id="languages">
            
          </div>

				
					<footer id="footer">
						<p class="copyright">&copy; daniel anderson. Design: <a href="https://html5up.net">HTML5 UP</a>. Powered by <a href="https://www.gohugo.io/">Hugo.</a></p>
					</footer>

			</div>
		
			<div id="bg"></div>

		
			<script src="/js/skel.min.js"></script>
			<script src="/js/util.js"></script>
			<script src="/js/main.js"></script>
			

	</body>
</html>

