---
title: Racial inequality and systemic racism
author: Daniel Anderson
date: '2020-06-13'
slug: racial-inequality-and-systemic-racism
categories:
  - Achievement Gap
tags: []
toc: false
lastmod: '2020-06-13T09:46:10-07:00'
output: 
  html_document:
    keep_md: true
---

The murders of George Floyd, Ahmaud Arbery, Breonna Taylor, and so, *so*, **so** many before them have brought into stark relief that if you have black or brown skin in this country, and particularly the former, you are at far greater risk for losing your life for... existing... than if your skin is white. It's unacceptable. Infuriating. Enraging. Depressing. As a country, we are mourning these deaths (while, as of the time of this writing, Breonna Taylor's murderers have still not been arrested). Our country is built on racism. Not only on the backs of slaves from the time the country was founded through Junteenth 1865, but also through purposeful legislation aimed at oppressing black and indigenous people of color.

This post is obviously a bit different than most. There will be no R code here. But I did want to share a few things. First, we are living, currently, in a systemically racist country. Our laws, infrastructure, medical systems, and our school systems are all built to differentially preference people who look like me---a white person. Second, I wanted to mention that I'm starting to work on a re-submission of a grant application focused around some of these issues, specifically academic achievement gaps in our public school systems.

## Systemic racism
[Richard Rothstein](https://www.epi.org/publication/the-racial-achievement-gap-segregated-schools-and-segregated-neighborhoods-a-constitutional-insult/) wrote my favorite article on this topic, in which he systematically breaks down what he calls "the myth of de facto segregation". In other words, segregation isn't just something that happened naturally. Rather, segregation was purposeful, of and by the law. Worse, the neighborhoods that black and brown people have been forced into for generations are under-resourced and overcrowded, often being re-zoned to allow for "mixed" use (people living in industrial sites), and having basic sanitation like garbage collection occurring less frequently than needed. Part of the problem is that black people in particular were not allowed to move into predominately white neighborhoods (redlining), even if they had the means. 

Corey Booker's parents were an exception to this rule, but [not without considerable challenges](https://heavy.com/news/2019/02/cory-bookers-mom-dad-parents/). The fair housing council ended up sending white people to look at houses for them. On the day they closed, the real estate agent became panicked, thinking he would lose his job. He bacame angry and punched Booker's lawyer, while setting a dog on Corey's father. Despite this, the Booker's were a rare exception, eventually closing on the house, which Corey says changed his family's future (see [here](https://www.imdb.com/title/tt8453102/)).

## Achievement gaps in schools
Our schools are also not equal. Schools in the aforementioned neighborhoods are often (surprise!) woefully under-resourced. Further, students of color (particularly black males) are [far more likely](https://www.tandfonline.com/doi/abs/10.1080/02796015.2011.12087730?casa_token=5LGh95rZXt4AAAAA:ZVM-g6uiGoE_iMSlIpCyPCvQj6HBR_i4vqJyYL9RrG4SPmY9fnDy7YjfxHq7bGJoXTadWIKyoaOXPQ) to be suspended or expelled from school. This practice contributes to the [school-to-prison pipeline](https://www.sciencedirect.com/science/article/pii/S019074091630278X?casa_token=95I2LdATCCwAAAAA:oZSXUTvoZ3CuAz5VQpX0yGBZLE6X1EPo2mxAK2WkQlNL-nNSycVX-tSWDzcs-yfv_VPUZcmsTFs), disproportionately pushing black and brown students out of school and into incarceration (beginning with the juvenile justice system). Further, if students are not in schools they are more likely to fall behind. Gaps in achievement between students of color and white students have existed "[for at least as long as we have thought to ask the question and had sufficient data to verify the answer](https://opinionator.blogs.nytimes.com/2013/04/27/no-rich-child-left-behind/)". Evidence from [Morris & Perry (2016)](https://academic.oup.com/socpro/article-abstract/63/1/68/1844875?redirectedFrom=fulltext) suggests that upwards of 20% of the black-white achievement gap may be accounted by disproportionality in school suspensions. 

Again, none of this is acceptable. If real change is going to occur, it has to be large-scale and systemic. Last year, I was unsuccessful in a grant application to the institute of education sciences to study variation in achievement gaps between schools. I'm happy to report, however, that we (myself and my colleagues) plan to resubmit this year. Our focus will change somewhat from the previous application, with more of a focus on kindergarten entry, students academic growth within the school year (rather than just between), and more focus on longitudinal outcomes and changes in achievement when students are not in school (i.e., differential changes in achievement occurring over the summer). Our hope is to better understand how practices like disproportionality in suspension/expulsion relate to differences in achievement (as well as absenteeism). However, we also hope to investigate the willingness of schools as organization (with a focus on school leaders, in particular) to change their practices related to suspension/expulsion, and what common barriers are preventing school leaders to enact these changes.

## The end
That's it for this post. Racism is wrong. That's obvious. But systemic racism can be harder to see if you're not affected by it every day, as so many are. Let's work to dismantle those structures.